package Swing;

import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAM116
 */
public class main extends javax.swing.JFrame {

    /*
    Variable para controlar que tipo de usuario está trabajando
    0-Invitado
    1-Alumno
    2-Diseñador
    3-Profesor
    4-Administrador
     */
    int nivelAcceso = 0;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setTitle("Gestor de Rutas RDosM2");
        mostrarLogo();
        this.setResizable(false); // Evita que la ventana se pueda redimensionar
    }

    public void mostrarLogo() {
        //Codigo tomado prestado del ejemplo completo
        java.net.URL imgUrl = getClass().getClassLoader().getResource("Imagenes/logo.jpeg");
        ImageIcon img = new ImageIcon(imgUrl);
        Icon icon = new ImageIcon(img.getImage().
                getScaledInstance(jLabelLogo.getWidth(),
                        jLabelLogo.getHeight(), img.getIconWidth()));
        this.jLabelLogo.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JButton();
        jButtonRegistrarse = new javax.swing.JButton();
        jButtonVerRutas = new javax.swing.JButton();
        jPanelInicioSesion = new javax.swing.JPanel();
        jPasswordFieldInicio = new javax.swing.JPasswordField();
        jTextFieldCorreoInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAccederInicio = new javax.swing.JButton();
        jButtonVolverInicio = new javax.swing.JButton();
        jPanelInicioSesion2 = new javax.swing.JPanel();
        jPasswordFieldInicio2 = new javax.swing.JPasswordField();
        jTextFieldCorreoInicio2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonAccederInicio2 = new javax.swing.JButton();
        jButtonVolverInicio2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidosRegistro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCorreoRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldRegistro1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldRegistro2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jButtonVolverRegistro = new javax.swing.JButton();
        choiceTipoUsuRegistro = new java.awt.Choice();
        jLabel10 = new javax.swing.JLabel();
        jButtonRegistrarseRegistro = new javax.swing.JButton();
        jPanelRutas = new javax.swing.JPanel();
        jButtonVolverRutas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPaneRutas = new javax.swing.JScrollPane();
        jTableRutas = new javax.swing.JTable();
        jButtonInfoRutas = new javax.swing.JButton();
        jPanelInfoRuta = new javax.swing.JPanel();
        jLabelNombreRuta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Rutas RDosM2");

        jButtonIniciarSesion.setText("Iniciar Sesion");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });

        jButtonVerRutas.setText("Ver Rutas");
        jButtonVerRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jButtonVerRutas)
                .addGap(50, 50, 50))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciarSesion)
                    .addComponent(jButtonVerRutas)
                    .addComponent(jButtonRegistrarse))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPrincipal, "card3");

        jPasswordFieldInicio.setToolTipText("");
        jPasswordFieldInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldInicioActionPerformed(evt);
            }
        });

        jTextFieldCorreoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoInicioActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo electronico");

        jLabel4.setText("Contraseña");

        jButtonAccederInicio.setText("Entrar");
        jButtonAccederInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederInicioActionPerformed(evt);
            }
        });

        jButtonVolverInicio.setText("Volver");
        jButtonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioSesionLayout = new javax.swing.GroupLayout(jPanelInicioSesion);
        jPanelInicioSesion.setLayout(jPanelInicioSesionLayout);
        jPanelInicioSesionLayout.setHorizontalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioSesionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonVolverInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAccederInicio)
                .addGap(32, 32, 32))
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel4))
                        .addComponent(jPasswordFieldInicio)
                        .addComponent(jTextFieldCorreoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioSesionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanelInicioSesionLayout.setVerticalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccederInicio)
                    .addComponent(jButtonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInicioSesion, "card2");

        jPasswordFieldInicio2.setToolTipText("");
        jPasswordFieldInicio2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldInicio2ActionPerformed(evt);
            }
        });

        jTextFieldCorreoInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoInicio2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Correo electronico");

        jLabel14.setText("Contraseña");

        jButtonAccederInicio2.setText("Entrar");
        jButtonAccederInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederInicio2ActionPerformed(evt);
            }
        });

        jButtonVolverInicio2.setText("Volver");
        jButtonVolverInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInicio2ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("        No se ha encontrado el usuario       ");

        javax.swing.GroupLayout jPanelInicioSesion2Layout = new javax.swing.GroupLayout(jPanelInicioSesion2);
        jPanelInicioSesion2.setLayout(jPanelInicioSesion2Layout);
        jPanelInicioSesion2Layout.setHorizontalGroup(
            jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioSesion2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonVolverInicio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAccederInicio2)
                .addGap(32, 32, 32))
            .addGroup(jPanelInicioSesion2Layout.createSequentialGroup()
                .addGroup(jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioSesion2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelInicioSesion2Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel14))
                                .addComponent(jPasswordFieldInicio2)
                                .addComponent(jTextFieldCorreoInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioSesion2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanelInicioSesion2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel15)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanelInicioSesion2Layout.setVerticalGroup(
            jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesion2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreoInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(25, 25, 25)
                .addGroup(jPanelInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccederInicio2)
                    .addComponent(jButtonVolverInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInicioSesion2, "card2");

        jLabel2.setText("Nombre");

        jTextFieldNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRegistroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registro");

        jTextFieldApellidosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosRegistroActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellidos");

        jTextFieldCorreoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoRegistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo Electronico");

        jPasswordFieldRegistro1.setToolTipText("");
        jPasswordFieldRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegistro1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Contraseña");

        jPasswordFieldRegistro2.setToolTipText("");
        jPasswordFieldRegistro2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegistro2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Confirmar Contraseña");

        jButtonVolverRegistro.setText("Volver");
        jButtonVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverRegistroActionPerformed(evt);
            }
        });

        jLabel10.setText("Nivel de Acceso");

        jButtonRegistrarseRegistro.setText("Registrarse");
        jButtonRegistrarseRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApellidosRegistro)
                                .addComponent(jTextFieldCorreoRegistro)
                                .addComponent(jPasswordFieldRegistro1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombreRegistro))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choiceTipoUsuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRegistro)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addComponent(jPasswordFieldRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarseRegistro)))
                .addContainerGap())
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceTipoUsuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidosRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonRegistrarseRegistro))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanelRegistro, "card4");

        jPanelRutas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelRutasComponentShown(evt);
            }
        });

        jButtonVolverRutas.setText("Volver");
        jButtonVolverRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverRutasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Rutas");

        jScrollPaneRutas.setPreferredSize(new java.awt.Dimension(100, 100));

        jTableRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Ruta", "Valoracion", "Esfuerzo", "Creacion"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jTableRutas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableRutas.setShowHorizontalLines(true);
        jScrollPaneRutas.setViewportView(jTableRutas);

        jButtonInfoRutas.setText("INFO");
        jButtonInfoRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRutasLayout = new javax.swing.GroupLayout(jPanelRutas);
        jPanelRutas.setLayout(jPanelRutasLayout);
        jPanelRutasLayout.setHorizontalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRutas, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(jPanelRutasLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInfoRutas)))
                .addContainerGap())
        );
        jPanelRutasLayout.setVerticalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRutasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRutasLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButtonInfoRutas))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelRutas, "card5");

        jLabelNombreRuta.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabelNombreRuta.setText("texto de muestra");
        jLabelNombreRuta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelNombreRutaComponentShown(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {
                "Nivel de Riesgo: ",
                "Nivel de Esfuerzo: ",
                "Tipo de Terreno: ",
                "Calidad de Indicaciones: ",
                "Accesibilidad: ",
                "Familiar",
                "Zona Geografica"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanelInfoRutaLayout = new javax.swing.GroupLayout(jPanelInfoRuta);
        jPanelInfoRuta.setLayout(jPanelInfoRutaLayout);
        jPanelInfoRutaLayout.setHorizontalGroup(
            jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreRuta)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelInfoRutaLayout.setVerticalGroup(
            jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelNombreRuta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInfoRuta, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelInicioSesion.setVisible(true);
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonVerRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerRutasActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelRutas.setVisible(true);
    }//GEN-LAST:event_jButtonVerRutasActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelRegistro.setVisible(true);
        choiceTipoUsuRegistro.add("Alumno");
        choiceTipoUsuRegistro.add("Diseñador");
        choiceTipoUsuRegistro.add("Profesor");
        choiceTipoUsuRegistro.add("Administrador");
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jPasswordFieldInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldInicioActionPerformed

    private void jButtonAccederInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccederInicioActionPerformed

    private void jButtonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInicioActionPerformed
        jPanelInicioSesion.setVisible(false);
        jPanelPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverInicioActionPerformed

    private void jTextFieldCorreoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoInicioActionPerformed

    private void jTextFieldNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreRegistroActionPerformed

    private void jTextFieldApellidosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosRegistroActionPerformed

    private void jTextFieldCorreoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoRegistroActionPerformed
    private void jPasswordFieldRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegistro1ActionPerformed

    private void jPasswordFieldRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegistro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegistro2ActionPerformed

    private void jButtonVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverRegistroActionPerformed
        jPanelRegistro.setVisible(false);
        jPanelPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverRegistroActionPerformed

    private void jButtonRegistrarseRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseRegistroActionPerformed
        // creamos las contraseñas y las casteamos a String para tratarlas en el if y ver si las contraseñas coinciden
        String contra1 = new String(jPasswordFieldRegistro1.getPassword());
        String contra2 = new String(jPasswordFieldRegistro2.getPassword());
        if (contra1.equals(contra2)) {
            JOptionPane.showMessageDialog(jPanelRegistro, "Su registro será completado cuando un administrador lo valide\nSe le enviará un mensaje al correo electronico", "Registro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jPanelRegistro, "Las contrasenas no coinciden\nAsegurese de que sean iguales", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Falta el codigo de creacion del usuario, la validacion de que está todo introducido
    }//GEN-LAST:event_jButtonRegistrarseRegistroActionPerformed

    private void jButtonVolverRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverRutasActionPerformed
        jPanelRutas.setVisible(false);
        jPanelPrincipal.setVisible(true);
        //Cuando haya menu de opciones, hay que controlar el nivel de acceso para volver a Nivel 0-> jPanelPrincipal  Otros niveles-> jPanelMenu (o como se llame)
    }//GEN-LAST:event_jButtonVolverRutasActionPerformed

    private void jButtonInfoRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoRutasActionPerformed
        //Id en la tabla de la ruta seleccionada, -1 si no se ha elegido ninguna
        int rutaIndex = jTableRutas.getSelectedRow();
        if (rutaIndex != -1) {
            //Cambio de ventana
            jPanelRutas.setVisible(false);
            jPanelInfoRuta.setVisible(true);
            //Usamos DefaultTableModel para sacar el nombre de la ruta
            DefaultTableModel modeloGeneral = (DefaultTableModel) jTableRutas.getModel();
            String nombreRuta = (String) modeloGeneral.getValueAt(rutaIndex, 0);
            //Ponemos el nombre de la ruta al label
            jLabelNombreRuta.setText(nombreRuta);
            //La gestion de la lista con la info
           
            //Implementar la informacion obtenida mediante la base de datos cuando sea posible
            //De momento voy a incluir datos de prueba
            

        } else {
            JOptionPane.showMessageDialog(jPanelInfoRuta, "No has seleccionado ninguna ruta", "", JOptionPane.QUESTION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInfoRutasActionPerformed

    private void jLabelNombreRutaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelNombreRutaComponentShown

    }//GEN-LAST:event_jLabelNombreRutaComponentShown

    private void jPanelRutasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelRutasComponentShown
        // Cogiendo el modelo y parseandolo a DefaultTableModel tenemos acceso a metodos que nos permiten añadir/eliminar/recoger filas de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableRutas.getModel();
        //Con esto no se puede mover el encabezado de la tabla
        jTableRutas.getTableHeader().setReorderingAllowed(false);
        //Eliminamos la filas que haya actualmente cargadas para actualizar el listado sin repetir rutas
        System.out.println(modelo.getRowCount());
        int numFilas = modelo.getRowCount();
        for (int i = 0; i < numFilas; i++) {
            modelo.removeRow(0);
        }

        //valores de pruebas
        for (int i = 0; i < 20; i++) {
            String[] infoEjemplo = {"Nombre", "3", String.valueOf(i), "12/05/25"};
            modelo.addRow(infoEjemplo);
        }
        String[] ejemplo = {"ejemploejemploejemploejemploejemploejemploeje", "ejemplo", "ejemplo", "ejemplo"};
        modelo.addRow(ejemplo);
    }//GEN-LAST:event_jPanelRutasComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordFieldInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldInicio2ActionPerformed

    private void jTextFieldCorreoInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoInicio2ActionPerformed

    private void jButtonAccederInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccederInicio2ActionPerformed

    private void jButtonVolverInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverInicio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceTipoUsuRegistro;
    private javax.swing.JButton jButtonAccederInicio;
    private javax.swing.JButton jButtonAccederInicio2;
    private javax.swing.JButton jButtonInfoRutas;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JButton jButtonRegistrarseRegistro;
    private javax.swing.JButton jButtonVerRutas;
    private javax.swing.JButton jButtonVolverInicio;
    private javax.swing.JButton jButtonVolverInicio2;
    private javax.swing.JButton jButtonVolverRegistro;
    private javax.swing.JButton jButtonVolverRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreRuta;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelInfoRuta;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JPanel jPanelInicioSesion2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanelRutas;
    private javax.swing.JPasswordField jPasswordFieldInicio;
    private javax.swing.JPasswordField jPasswordFieldInicio2;
    private javax.swing.JPasswordField jPasswordFieldRegistro1;
    private javax.swing.JPasswordField jPasswordFieldRegistro2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneRutas;
    private javax.swing.JTable jTableRutas;
    private javax.swing.JTextField jTextFieldApellidosRegistro;
    private javax.swing.JTextField jTextFieldCorreoInicio;
    private javax.swing.JTextField jTextFieldCorreoInicio2;
    private javax.swing.JTextField jTextFieldCorreoRegistro;
    private javax.swing.JTextField jTextFieldNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
