package Swing;

import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAM116
 */
public class main extends javax.swing.JFrame {

    /*
    Variable para controlar que tipo de usuario está trabajando
    0-Invitado
    1-Alumno
    2-Diseñador
    3-Profesor
    4-Administrador
     */
    int nivelAcceso = 0;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setTitle("Gestor de Rutas RDosM2");
        mostrarLogo();
        this.setResizable(false); // Evita que la ventana se pueda redimensionar
    }

    public void mostrarLogo() {
        //Codigo tomado prestado del ejemplo completo
        java.net.URL imgUrl = getClass().getClassLoader().getResource("Imagenes/logo.jpeg");
        ImageIcon img = new ImageIcon(imgUrl);
        Icon icon = new ImageIcon(img.getImage().
                getScaledInstance(jLabelLogo.getWidth(),
                        jLabelLogo.getHeight(), img.getIconWidth()));
        this.jLabelLogo.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JButton();
        jButtonRegistrarse = new javax.swing.JButton();
        jButtonVerRutas = new javax.swing.JButton();
        jPanelInicioSesion = new javax.swing.JPanel();
        jPasswordFieldInicio = new javax.swing.JPasswordField();
        jTextFieldCorreoInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAccederInicio = new javax.swing.JButton();
        jButtonVolverInicio = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidosRegistro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCorreoRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldRegistro1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldRegistro2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jButtonVolverRegistro = new javax.swing.JButton();
        choiceTipoUsuRegistro = new java.awt.Choice();
        jLabel10 = new javax.swing.JLabel();
        jButtonRegistrarseRegistro = new javax.swing.JButton();
        jPanelRutas = new javax.swing.JPanel();
        jButtonVolverRutas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPaneRutas = new javax.swing.JScrollPane();
        jTableRutas = new javax.swing.JTable();
        jButtonInfoRutas = new javax.swing.JButton();
        jPanelInfoRuta = new javax.swing.JPanel();
        jLabelNombreRutaInfo = new javax.swing.JLabel();
        jTableInfo = new javax.swing.JTable();
        jButtonVolverInfo = new javax.swing.JButton();
        jButtonReseñarInfo = new javax.swing.JButton();
        jButtonValorarInfo = new javax.swing.JButton();
        jButtonVerValResInfo = new javax.swing.JButton();
        jPanelValoracionesAdminRuta = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButtonVolverValoracionesAdmin = new javax.swing.JButton();
        jScrollPaneResenasAdmin = new javax.swing.JScrollPane();
        jTableResenasAdmin = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPaneValTecnAdmin = new javax.swing.JScrollPane();
        jTableValTecnAdmin = new javax.swing.JTable();
        jPanelValoracionesUsuRuta = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButtonVolverValoracionesUsu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPaneResenasUsu = new javax.swing.JScrollPane();
        jTableResenasUsu = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jScrollPaneValTecnUsu = new javax.swing.JScrollPane();
        jTableValTecnUsu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Rutas RDosM2");

        jButtonIniciarSesion.setText("Iniciar Sesion");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });

        jButtonVerRutas.setText("Ver Rutas");
        jButtonVerRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonIniciarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarse)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVerRutas)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciarSesion)
                    .addComponent(jButtonVerRutas)
                    .addComponent(jButtonRegistrarse))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPrincipal, "card3");

        jPasswordFieldInicio.setToolTipText("");
        jPasswordFieldInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldInicioActionPerformed(evt);
            }
        });

        jTextFieldCorreoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoInicioActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo electronico");

        jLabel4.setText("Contraseña");

        jButtonAccederInicio.setText("Entrar");
        jButtonAccederInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederInicioActionPerformed(evt);
            }
        });

        jButtonVolverInicio.setText("Volver");
        jButtonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInicioActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("   No se ha encontrado el usuario.   ");

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Asegúrese que los datos introducidos sean correctos");

        javax.swing.GroupLayout jPanelInicioSesionLayout = new javax.swing.GroupLayout(jPanelInicioSesion);
        jPanelInicioSesion.setLayout(jPanelInicioSesionLayout);
        jPanelInicioSesionLayout.setHorizontalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonVolverInicio)
                        .addGap(235, 235, 235)
                        .addComponent(jButtonAccederInicio))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel4))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel13))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel12)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelInicioSesionLayout.setVerticalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccederInicio)
                    .addComponent(jButtonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInicioSesion, "card2");

        jLabel2.setText("Nombre");

        jTextFieldNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRegistroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registro");

        jTextFieldApellidosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosRegistroActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellidos");

        jTextFieldCorreoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoRegistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo Electronico");

        jPasswordFieldRegistro1.setToolTipText("");
        jPasswordFieldRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegistro1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Contraseña");

        jPasswordFieldRegistro2.setToolTipText("");
        jPasswordFieldRegistro2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordFieldRegistro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegistro2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Confirmar Contraseña");

        jButtonVolverRegistro.setText("Volver");
        jButtonVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverRegistroActionPerformed(evt);
            }
        });

        jLabel10.setText("Nivel de Acceso");

        jButtonRegistrarseRegistro.setText("Registrarse");
        jButtonRegistrarseRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 354, Short.MAX_VALUE))
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApellidosRegistro)
                                .addComponent(jTextFieldCorreoRegistro)
                                .addComponent(jPasswordFieldRegistro1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombreRegistro))
                            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choiceTipoUsuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRegistro)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addGap(0, 196, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarseRegistro)))
                .addContainerGap())
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceTipoUsuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldApellidosRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButtonRegistrarseRegistro))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanelRegistro, "card4");

        jPanelRutas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelRutasComponentShown(evt);
            }
        });

        jButtonVolverRutas.setText("Volver");
        jButtonVolverRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverRutasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Rutas");

        jScrollPaneRutas.setPreferredSize(new java.awt.Dimension(100, 100));

        jTableRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Ruta", "Valoracion", "Esfuerzo", "Creacion"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jTableRutas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableRutas.setShowHorizontalLines(true);
        jScrollPaneRutas.setViewportView(jTableRutas);

        jButtonInfoRutas.setText("INFO");
        jButtonInfoRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRutasLayout = new javax.swing.GroupLayout(jPanelRutas);
        jPanelRutas.setLayout(jPanelRutasLayout);
        jPanelRutasLayout.setHorizontalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRutas, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanelRutasLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonInfoRutas)))
                .addContainerGap())
        );
        jPanelRutasLayout.setVerticalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRutasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRutasLayout.createSequentialGroup()
                        .addComponent(jButtonVolverRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jButtonInfoRutas))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelRutas, "card5");

        jPanelInfoRuta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelInfoRutaComponentShown(evt);
            }
        });

        jLabelNombreRutaInfo.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabelNombreRutaInfo.setText("texto de muestra");
        jLabelNombreRutaInfo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelNombreRutaInfoComponentShown(evt);
            }
        });

        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Distancia", null},
                {"Duracion Estimada", null},
                {"Clasificacion", null},
                {"Nivel de Riesgo", null},
                {"Nivel de Esfuerzo", null},
                {"Tipo de Terreno", null},
                {"Zona", null},
                {null,"Escala 1-5"},
                {"Indicaciones", null},
                {"Accesibilidad", null},
                {"Familiar", null},
                {"Valoracion Media", null}

            },
            new Object[] {"nombre","info"}
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        jButtonVolverInfo.setText("Volver");
        jButtonVolverInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInfoActionPerformed(evt);
            }
        });

        jButtonReseñarInfo.setText("Reseñar");
        jButtonReseñarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReseñarInfoActionPerformed(evt);
            }
        });

        jButtonValorarInfo.setText("Valorar");
        jButtonValorarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValorarInfoActionPerformed(evt);
            }
        });

        jButtonVerValResInfo.setText("Ver Valoraciones/Reseñas");
        jButtonVerValResInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerValResInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoRutaLayout = new javax.swing.GroupLayout(jPanelInfoRuta);
        jPanelInfoRuta.setLayout(jPanelInfoRutaLayout);
        jPanelInfoRutaLayout.setHorizontalGroup(
            jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreRutaInfo)
                    .addComponent(jButtonVolverInfo)
                    .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                        .addComponent(jTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVerValResInfo))
                            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonReseñarInfo)
                                    .addComponent(jButtonValorarInfo))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoRutaLayout.setVerticalGroup(
            jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolverInfo)
                .addGap(2, 2, 2)
                .addComponent(jLabelNombreRutaInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoRutaLayout.createSequentialGroup()
                        .addComponent(jButtonVerValResInfo)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonReseñarInfo)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonValorarInfo)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInfoRuta, "card6");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButtonVolverValoracionesAdmin.setText("Volver");
        jButtonVolverValoracionesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverValoracionesAdminActionPerformed(evt);
            }
        });

        jTableResenasAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Valoración (1-5)", "Fecha", "Comentario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneResenasAdmin.setViewportView(jTableResenasAdmin);
        if (jTableResenasAdmin.getColumnModel().getColumnCount() > 0) {
            jTableResenasAdmin.getColumnModel().getColumn(0).setHeaderValue("Usuario");
        }

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("VALORACIONES");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Reseñas");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Valoraciones técnicas");

        jTableValTecnAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "DIficultad (1-5)", "Belleza (1-5)", "Interés cultural (1-5)", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneValTecnAdmin.setViewportView(jTableValTecnAdmin);
        if (jTableValTecnAdmin.getColumnModel().getColumnCount() > 0) {
            jTableValTecnAdmin.getColumnModel().getColumn(0).setHeaderValue("Usuario");
        }

        javax.swing.GroupLayout jPanelValoracionesAdminRutaLayout = new javax.swing.GroupLayout(jPanelValoracionesAdminRuta);
        jPanelValoracionesAdminRuta.setLayout(jPanelValoracionesAdminRutaLayout);
        jPanelValoracionesAdminRutaLayout.setHorizontalGroup(
            jPanelValoracionesAdminRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelValoracionesAdminRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneValTecnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jScrollPaneResenasAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                        .addComponent(jButtonVolverValoracionesAdmin)
                        .addGroup(jPanelValoracionesAdminRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel14))
                            .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel15)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelValoracionesAdminRutaLayout.setVerticalGroup(
            jPanelValoracionesAdminRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGroup(jPanelValoracionesAdminRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15))
                    .addGroup(jPanelValoracionesAdminRutaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVolverValoracionesAdmin)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResenasAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneValTecnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelValoracionesAdminRuta, "card7");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("VALORACIONES");

        jButtonVolverValoracionesUsu.setText("Volver");
        jButtonVolverValoracionesUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverValoracionesUsuActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Reseñas");

        jTableResenasUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Valoración (1-5)", "Fecha", "Comentario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneResenasUsu.setViewportView(jTableResenasUsu);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Valoraciones técnicas");

        jTableValTecnUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DIficultad (1-5)", "Belleza (1-5)", "Interés cultural (1-5)", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneValTecnUsu.setViewportView(jTableValTecnUsu);

        javax.swing.GroupLayout jPanelValoracionesUsuRutaLayout = new javax.swing.GroupLayout(jPanelValoracionesUsuRuta);
        jPanelValoracionesUsuRuta.setLayout(jPanelValoracionesUsuRutaLayout);
        jPanelValoracionesUsuRutaLayout.setHorizontalGroup(
            jPanelValoracionesUsuRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValoracionesUsuRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelValoracionesUsuRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneValTecnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelValoracionesUsuRutaLayout.createSequentialGroup()
                        .addGroup(jPanelValoracionesUsuRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneResenasUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addGroup(jPanelValoracionesUsuRutaLayout.createSequentialGroup()
                                .addComponent(jButtonVolverValoracionesUsu)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelValoracionesUsuRutaLayout.setVerticalGroup(
            jPanelValoracionesUsuRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValoracionesUsuRutaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelValoracionesUsuRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVolverValoracionesUsu)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResenasUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneValTecnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanelValoracionesUsuRuta, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelInicioSesion.setVisible(true);
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonVerRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerRutasActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelRutas.setVisible(true);
    }//GEN-LAST:event_jButtonVerRutasActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        jPanelPrincipal.setVisible(false);
        jPanelRegistro.setVisible(true);
        choiceTipoUsuRegistro.add("Alumno");
        choiceTipoUsuRegistro.add("Diseñador");
        choiceTipoUsuRegistro.add("Profesor");
        choiceTipoUsuRegistro.add("Administrador");
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jPasswordFieldInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldInicioActionPerformed

    private void jButtonAccederInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederInicioActionPerformed
        // TODO add your handling code here:
        /* Dejamos los jLabel invisibles hasta que le de al boton, entonces en el if se comprobara que el usuario
        escrito existe, si no existe se veran los jLabel informando de ello*/
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        // if(){
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        //}
    }//GEN-LAST:event_jButtonAccederInicioActionPerformed

    private void jButtonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInicioActionPerformed
        jPanelInicioSesion.setVisible(false);
        jPanelPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverInicioActionPerformed

    private void jTextFieldCorreoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoInicioActionPerformed

    private void jTextFieldNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreRegistroActionPerformed

    private void jTextFieldApellidosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosRegistroActionPerformed

    private void jTextFieldCorreoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoRegistroActionPerformed
    private void jPasswordFieldRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegistro1ActionPerformed

    private void jPasswordFieldRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegistro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegistro2ActionPerformed

    private void jButtonVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverRegistroActionPerformed
        jPanelRegistro.setVisible(false);
        jPanelPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverRegistroActionPerformed

    private void jButtonRegistrarseRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseRegistroActionPerformed
        // creamos las contraseñas y las casteamos a String para tratarlas en el if y ver si las contraseñas coinciden
        String contra1 = new String(jPasswordFieldRegistro1.getPassword());
        String contra2 = new String(jPasswordFieldRegistro2.getPassword());
        if (contra1.equals(contra2)) {
            JOptionPane.showMessageDialog(jPanelRegistro, "Su registro será completado cuando un administrador lo valide\nSe le enviará un mensaje al correo electronico", "Registro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jPanelRegistro, "Las contrasenas no coinciden\nAsegurese de que sean iguales", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Falta el codigo de creacion del usuario, la validacion de que está todo introducido
    }//GEN-LAST:event_jButtonRegistrarseRegistroActionPerformed

    private void jButtonVolverRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverRutasActionPerformed
        jPanelRutas.setVisible(false);
        if (nivelAcceso == 0) {
            jPanelPrincipal.setVisible(true);
        } else {
            //Cuando haya menu de opciones, hay que controlar el nivel de acceso para volver a Nivel 0-> jPanelPrincipal  Otros niveles-> jPanelMenu (o como se llame)
        }
    }//GEN-LAST:event_jButtonVolverRutasActionPerformed

    private void jButtonInfoRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoRutasActionPerformed
        //Id en la tabla de la ruta seleccionada, -1 si no se ha elegido ninguna
        int rutaIndex = jTableRutas.getSelectedRow();
        if (rutaIndex != -1) {
            //Cambio de ventana
            jPanelRutas.setVisible(false);
            jPanelInfoRuta.setVisible(true);
            //Usamos DefaultTableModel para sacar el nombre de la ruta
            DefaultTableModel modeloGeneral = (DefaultTableModel) jTableRutas.getModel();
            String nombreRuta = (String) modeloGeneral.getValueAt(rutaIndex, 0);
            //Ponemos el nombre de la ruta al label
            jLabelNombreRutaInfo.setText(nombreRuta);
            //La gestion de la tabla con la info

            //Implementar la informacion obtenida mediante la base de datos cuando sea posible
            //De momento voy a incluir datos de prueba
        } else {
            JOptionPane.showMessageDialog(jPanelInfoRuta, "No has seleccionado ninguna ruta", "", JOptionPane.QUESTION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInfoRutasActionPerformed

    private void jPanelRutasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelRutasComponentShown
        // Cogiendo el modelo y parseandolo a DefaultTableModel tenemos acceso a metodos que nos permiten añadir/eliminar/recoger filas de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableRutas.getModel();
        //Con esto no se puede mover el encabezado de la tabla
        jTableRutas.getTableHeader().setReorderingAllowed(false);
        //Eliminamos la filas que haya actualmente cargadas para actualizar el listado sin repetir rutas
        int numFilas = modelo.getRowCount();
        for (int i = 0; i < numFilas; i++) {
            modelo.removeRow(0);
        }

        //valores de pruebas
        for (int i = 0; i < 20; i++) {
            String[] infoEjemplo = {"Nombre", "3", String.valueOf(i), "12/05/25"};
            modelo.addRow(infoEjemplo);
        }
        String[] ejemplo = {"ejemploejemploejemploejemploejemploejemploeje", "ejemplo", "ejemplo", "ejemplo"};
        modelo.addRow(ejemplo);
    }//GEN-LAST:event_jPanelRutasComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonReseñarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReseñarInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReseñarInfoActionPerformed

    private void jButtonVolverInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInfoActionPerformed
        jPanelInfoRuta.setVisible(false);
        jPanelRutas.setVisible(true);
    }//GEN-LAST:event_jButtonVolverInfoActionPerformed

    private void jLabelNombreRutaInfoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelNombreRutaInfoComponentShown

    }//GEN-LAST:event_jLabelNombreRutaInfoComponentShown

    private void jPanelInfoRutaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelInfoRutaComponentShown
        //Control de visibilidad de los botones
        if (nivelAcceso < 1) {
            jButtonVerValResInfo.setVisible(true);
            jButtonReseñarInfo.setVisible(false);
            jButtonValorarInfo.setVisible(false);
        } else if (nivelAcceso < 2) {
            jButtonVerValResInfo.setVisible(true);
            jButtonReseñarInfo.setVisible(true);
            jButtonValorarInfo.setVisible(false);
        } else {
            jButtonVerValResInfo.setVisible(true);
            jButtonReseñarInfo.setVisible(true);
            jButtonValorarInfo.setVisible(true);
        }

    }//GEN-LAST:event_jPanelInfoRutaComponentShown

    private void jButtonValorarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValorarInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValorarInfoActionPerformed

    private void jButtonVerValResInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerValResInfoActionPerformed
        // TODO add your handling code here:
        jPanelInfoRuta.setVisible(false);
        // si es administrador las tablas incluyen la columna de usuario porque solo ellos pueden ver quien hace las valoraciones
        if (nivelAcceso == 4) {
            jPanelValoracionesAdminRuta.setVisible(true);
            // creamos reseñas de prueba para el admin
            DefaultTableModel modelo1 = (DefaultTableModel) jTableResenasAdmin.getModel();
            int numFilas = modelo1.getRowCount();
            for (int i = 0; i < numFilas; i++) {
                modelo1.removeRow(0);
            }
            for (int i = 0; i < 20; i++) {
                String[] infoEjemplo = {"Usuario", "5", "14/05/25", String.valueOf(i)};
                modelo1.addRow(infoEjemplo);
            }
            // creamos valoraciones tecnicas de prueba para el admin
            DefaultTableModel modelo2 = (DefaultTableModel) jTableValTecnAdmin.getModel();
            int numFilas2 = modelo2.getRowCount();
            for (int i = 0; i < numFilas2; i++) {
                modelo2.removeRow(0);
            }
            for (int i = 0; i < 20; i++) {
                String[] infoEjemplo = {"Usuario", "2", "4", "3", "14/05/25"};
                modelo2.addRow(infoEjemplo);
            }
            // cualquier otro tipo de usuario no puede ver quien hace las valoraciones
        } else if (nivelAcceso < 4) {
            jPanelValoracionesUsuRuta.setVisible(true);
            // creamos las reseñas de prueba para otros usuarios
            DefaultTableModel modelo3 = (DefaultTableModel) jTableResenasUsu.getModel();
            int numFilas3 = modelo3.getRowCount();
            for (int i = 0; i < numFilas3; i++) {
                modelo3.removeRow(0);
            }
            for (int i = 0; i < 20; i++) {
                String[] infoEjemplo = {"4", "14/05/25", String.valueOf(i)};
                modelo3.addRow(infoEjemplo);
            }
            // creamos valoraciones tecnicas de prueba para otros usuarios
            DefaultTableModel modelo4 = (DefaultTableModel) jTableValTecnUsu.getModel();
            int numFilas4 = modelo4.getRowCount();
            for (int i = 0; i < numFilas4; i++) {
                modelo4.removeRow(0);
            }
            for (int i = 0; i < 20; i++) {
                String[] infoEjemplo = {"2", "4", "3", "14/05/25"};
                modelo4.addRow(infoEjemplo);
            }
        }
    }//GEN-LAST:event_jButtonVerValResInfoActionPerformed

    private void jButtonVolverValoracionesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverValoracionesAdminActionPerformed
        // TODO add your handling code here:
        jPanelValoracionesAdminRuta.setVisible(false);
        jPanelInfoRuta.setVisible(true);
    }//GEN-LAST:event_jButtonVolverValoracionesAdminActionPerformed

    private void jButtonVolverValoracionesUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverValoracionesUsuActionPerformed
        // TODO add your handling code here:
        jPanelValoracionesUsuRuta.setVisible(false);
        jPanelInfoRuta.setVisible(true);
    }//GEN-LAST:event_jButtonVolverValoracionesUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceTipoUsuRegistro;
    private javax.swing.JButton jButtonAccederInicio;
    private javax.swing.JButton jButtonInfoRutas;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JButton jButtonRegistrarseRegistro;
    private javax.swing.JButton jButtonReseñarInfo;
    private javax.swing.JButton jButtonValorarInfo;
    private javax.swing.JButton jButtonVerRutas;
    private javax.swing.JButton jButtonVerValResInfo;
    private javax.swing.JButton jButtonVolverInfo;
    private javax.swing.JButton jButtonVolverInicio;
    private javax.swing.JButton jButtonVolverRegistro;
    private javax.swing.JButton jButtonVolverRutas;
    private javax.swing.JButton jButtonVolverValoracionesAdmin;
    private javax.swing.JButton jButtonVolverValoracionesUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreRutaInfo;
    private javax.swing.JPanel jPanelInfoRuta;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanelRutas;
    private javax.swing.JPanel jPanelValoracionesAdminRuta;
    private javax.swing.JPanel jPanelValoracionesUsuRuta;
    private javax.swing.JPasswordField jPasswordFieldInicio;
    private javax.swing.JPasswordField jPasswordFieldRegistro1;
    private javax.swing.JPasswordField jPasswordFieldRegistro2;
    private javax.swing.JScrollPane jScrollPaneResenasAdmin;
    private javax.swing.JScrollPane jScrollPaneResenasUsu;
    private javax.swing.JScrollPane jScrollPaneRutas;
    private javax.swing.JScrollPane jScrollPaneValTecnAdmin;
    private javax.swing.JScrollPane jScrollPaneValTecnUsu;
    private javax.swing.JTable jTableInfo;
    private javax.swing.JTable jTableResenasAdmin;
    private javax.swing.JTable jTableResenasUsu;
    private javax.swing.JTable jTableRutas;
    private javax.swing.JTable jTableValTecnAdmin;
    private javax.swing.JTable jTableValTecnUsu;
    private javax.swing.JTextField jTextFieldApellidosRegistro;
    private javax.swing.JTextField jTextFieldCorreoInicio;
    private javax.swing.JTextField jTextFieldCorreoRegistro;
    private javax.swing.JTextField jTextFieldNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
